### PR TITLE
tool: added sigtran decode/re-encode testing script

### PR DESCRIPTION
**Pull request by H21lab**
Maybe this script can be useful to tests the pycrate encoder/decoder. The script is written for MAP_TCAP (BER encoding) but the similar approach can be used also for other protocols.

### CODE REVIEW

**Comment by mitshell** [comment]
Hi, thank you very much for your proposal.

Some general remarks:
- pycrate supports both Python2 and 3, so should any new part or extension
- the script looks more like something for testing (hence, for the ./test/ subdirectory) than a complete tool with a proper cmd-line interface
- It misses some concrete TCAP-MAP data to consume :)

And more precise reflexions:
- BER being far from canonical, there is high chances that a reencoding won't match an original TCAP-MAP buffer, this does not mean the BER encoder is incorrect
- You import the whole pycrate_asn1c.proc part, but I am unsure it is used in your script ; take care also that some objects from asn1c have same name as some from asn1rt, but not the same interface / behaviour
- fuzzing the decoder seems like a good idea ; you should only get crappy decoded data or ASN1Err exceptions. In case you get something else on this, do not hesitate to submit a bug report.

I won't merge your proposal as is, and will be happy to review any modified version if you submit one.

**Comment by H21lab** [comment]
Hi, thank you for your feedback. 
I hope I have corrected the above: 
- Script is now in test folder and python3
- Regarding the test data, I also put into res folder json file (I used some publicly available pcaps from pcapr to generate this. I hope it is ok and the description is in the readme. If not let me know and I can try to craft some)
- for BER encoding I agree, now only decoded objects is compared not hex
- removed the not necessary imports

I think it is raising also few other exceptions, not only ASN1Err exception, I will try to follow it in the separate issue.

**Comment by mitshell** [comment]
The test code is looking fine, thanks a lot for it !

I have been working a little bit on the pcapr data : some tcap_raw fields are actually not corresponding to MAP data, hence leading to an error with the TCAP-MAP BER decoder. Do you have any information on what protocol it can be, or if we can find it from the TCAP header ? Here is the TCAP header (dialoguePortion) info from the 1st tcap_raw packet which is not a TCAP-MAP packet:

```
In [6]: TC.from_ber(b)
----------------------------
otid
b'\x12\x00\xff'
----------------------------
direct-reference
(0, 0, 17, 773, 1, 1, 1)
----------------------------
protocol-version
(1, 1)
----------------------------
application-context-name
(1, 2, 826, 0, 1249, 51, 1, 1, 1, 0, 1)
----------------------------
result
0
----------------------------
dialogue-service-user
0
----------------------------
result-source-diagnostic
('dialogue-service-user', 0)
----------------------------
dialogueResponse
{'result': 0, 'protocol-version': (1, 1), 'application-context-name': (1, 2, 826, 0, 1249, 51, 1, 1, 1, 0, 1), 'result-source-diagnostic': ('dialogue-service-user', 0)}
----------------------------
Type
('dialogueResponse', {'result': 0, 'protocol-version': (1, 1), 'application-context-name': (1, 2, 826, 0, 1249, 51, 1, 1, 1, 0, 1), 'result-source-diagnostic': ('dialogue-service-user', 0)})
----------------------------
single-ASN1-type
('DialoguePDU', ('dialogueResponse', {'result': 0, 'protocol-version': (1, 1), 'application-context-name': (1, 2, 826, 0, 1249, 51, 1, 1, 1, 0, 1), 'result-source-diagnostic': ('dialogue-service-user', 0)}))
----------------------------
encoding
('single-ASN1-type', ('DialoguePDU', ('dialogueResponse', {'result': 0, 'protocol-version': (1, 1), 'application-context-name': (1, 2, 826, 0, 1249, 51, 1, 1, 1, 0, 1), 'result-source-diagnostic': ('dialogue-service-user', 0)})))
----------------------------
dialoguePortion
{'encoding': ('single-ASN1-type', ('DialoguePDU', ('dialogueResponse', {'result': 0, 'protocol-version': (1, 1), 'application-context-name': (1, 2, 826, 0, 1249, 51, 1, 1, 1, 0, 1), 'result-source-diagnostic': ('dialogue-service-user', 0)}))), 'direct-reference': (0, 0, 17, 773, 1, 1, 1)}
----------------------------
present
1
----------------------------
invokeId
('present', 1)
----------------------------
local
23
----------------------------
opcode
('local', 23)
OPEN._decode_ber_cont: TCAP-MAP-Message.begin.components._item_.basicROS.invoke.argument, decoding failed for the selected object ArgumentType [UpdateGprsLocationArg] (ArgumentType: missing mandatory component, imsi)
---------------------------------------------------------------------------
CharpyErr                                 Traceback (most recent call last)
<ipython-input-6-1374a9514089> in <module>()
----> 1 TC.from_ber(b)
[...]
```

On the other side, the raw BER decoder can decode it fine. From the json file, it seems tshark is also decoding them fine as blobs over TCAP:
```
$ tools/pycrate_berdecode.py -s 6282027348031200ff6b2f282d060700118605010101a022612080020780a10e060c2a863a008961330101010001a203020100a305a1030201006c80a124020101020117301ca01a300b800112810100a203800101300b800111810100a203800101a112020102020113300a8300be06820101840102a11502010302012f300da00ba009a0048002106781017fa143020104020120303bc10702905044040020e203800102c40702905044040020c5020402a009040701105044040020a40a3008020105a1030201019e0783134514064206a11d02010502012e3015a00ea10c810100820400000000830100a103800102a1200201060201220418a103800102a311a003800103a40a04080101105044040020a143020107020120303bc10702905044040020e203800103c40702905044040020c5020402a009040701105044614000a40a3008020105a1030201019e0783134514064206a11d02010802012e3015a00ea10c810100820400000000830100a103800103a1200201090201220418a103800103a311a003800103a40a04080101105044040020a15d02010a0201173055a053300b8001f9810100a203800103300b80010d810100a203800103300b8001fb810100a203800103301080010e810100a203800103be03810114300b80010f810100a203800103300b8001fa810101a203800103a15d02010b0201173055a053300b8001f9810100a203800102300b80010d810100a203800102300b8001fb810100a203800102301080010e810100a203800102be03810114300b80010f810100a203800102300b8001fa810101a203800102a10d02010c02011fe105a103800102a10d02010d02011fe105a1038001030000

---------------------------- object 0----------------------------

[(1, 2),
 [[(1, 8), '\x12\x00\xff'],
  [(1, 11),
   [[(0, 8, 'INSTANCE OF, EXTERNAL'),
     [[(0, 6, 'OBJECT IDENTIFIER'), '\x00\x11\x86\x05\x01\x01\x01'],
      [(2, 0),
       [[(1, 1),
         [[(2, 0), '\x07\x80'],
          [(2, 1),
           [[(0, 6, 'OBJECT IDENTIFIER'),
             '*\x86:\x00\x89a3\x01\x01\x01\x00\x01']]],
          [(2, 2), [[(0, 2, 'INTEGER'), '\x00']]],
          [(2, 3), [[(2, 1), [[(0, 2, 'INTEGER'), '\x00']]]]]]]]]]]]],
  [(1, 12),
   [[(2, 1),
     [[(0, 2, 'INTEGER'), '\x01'],
      [(0, 2, 'INTEGER'), '\x17'],
      [(0, 16, 'SEQUENCE, SEQUENCE OF'),
       [[(2, 0),
         [[(0, 16, 'SEQUENCE, SEQUENCE OF'),
           [[(2, 0), '\x12'],
            [(2, 1), '\x00'],
            [(2, 2), [[(2, 0), '\x01']]]]],
          [(0, 16, 'SEQUENCE, SEQUENCE OF'),
           [[(2, 0), '\x11'],
            [(2, 1), '\x00'],
            [(2, 2), [[(2, 0), '\x01']]]]]]]]]]],
    [(2, 1),
     [[(0, 2, 'INTEGER'), '\x02'],
      [(0, 2, 'INTEGER'), '\x13'],
      [(0, 16, 'SEQUENCE, SEQUENCE OF'),
       [[(2, 3), ''], [(2, 30), [[(2, 2), '\x01'], [(2, 4), '\x02']]]]]]],
    [(2, 1),
     [[(0, 2, 'INTEGER'), '\x03'],
      [(0, 2, 'INTEGER'), '/'],
      [(0, 16, 'SEQUENCE, SEQUENCE OF'),
       [[(2, 0),
         [[(2, 0), [[(2, 0), [[(2, 0), '\x10g']]], [(2, 1), '\x7f']]]]]]]]],
    [(2, 1),
     [[(0, 2, 'INTEGER'), '\x04'],
      [(0, 2, 'INTEGER'), ' '],
      [(0, 16, 'SEQUENCE, SEQUENCE OF'),
       [[(3, 1), '\x02\x90PD\x04\x00 '],
        [(3, 2), [[(2, 0), '\x02']]],
        [(3, 4), '\x02\x90PD\x04\x00 '],
        [(3, 5), '\x04\x02'],
        [(2, 0), [[(0, 4, 'OCTET STRING'), '\x01\x10PD\x04\x00 ']]],
        [(2, 4),
         [[(0, 16, 'SEQUENCE, SEQUENCE OF'),
           [[(0, 2, 'INTEGER'), '\x05'],
            [(2, 1), [[(0, 2, 'INTEGER'), '\x01']]]]]]],
        [(2, 30), '\x83\x13E\x14\x06B\x06']]]]],
    [(2, 1),
     [[(0, 2, 'INTEGER'), '\x05'],
      [(0, 2, 'INTEGER'), '.'],
      [(0, 16, 'SEQUENCE, SEQUENCE OF'),
       [[(2, 0),
         [[(2, 1),
           [[(2, 1), '\x00'],
            [(2, 2), '\x00\x00\x00\x00'],
            [(2, 3), '\x00']]]]],
        [(2, 1), [[(2, 0), '\x02']]]]]]],
    [(2, 1),
     [[(0, 2, 'INTEGER'), '\x06'],
      [(0, 2, 'INTEGER'), '"'],
      [(0, 4, 'OCTET STRING'),
       '\xa1\x03\x80\x01\x02\xa3\x11\xa0\x03\x80\x01\x03\xa4\n\x04\x08\x01\x01\x10PD\x04\x00 ']]],
    [(2, 1),
     [[(0, 2, 'INTEGER'), '\x07'],
      [(0, 2, 'INTEGER'), ' '],
      [(0, 16, 'SEQUENCE, SEQUENCE OF'),
       [[(3, 1), '\x02\x90PD\x04\x00 '],
        [(3, 2), [[(2, 0), '\x03']]],
        [(3, 4), '\x02\x90PD\x04\x00 '],
        [(3, 5), '\x04\x02'],
        [(2, 0), [[(0, 4, 'OCTET STRING'), '\x01\x10PDa@\x00']]],
        [(2, 4),
         [[(0, 16, 'SEQUENCE, SEQUENCE OF'),
           [[(0, 2, 'INTEGER'), '\x05'],
            [(2, 1), [[(0, 2, 'INTEGER'), '\x01']]]]]]],
        [(2, 30), '\x83\x13E\x14\x06B\x06']]]]],
    [(2, 1),
     [[(0, 2, 'INTEGER'), '\x08'],
      [(0, 2, 'INTEGER'), '.'],
      [(0, 16, 'SEQUENCE, SEQUENCE OF'),
       [[(2, 0),
         [[(2, 1),
           [[(2, 1), '\x00'],
            [(2, 2), '\x00\x00\x00\x00'],
            [(2, 3), '\x00']]]]],
        [(2, 1), [[(2, 0), '\x03']]]]]]],
    [(2, 1),
     [[(0, 2, 'INTEGER'), '\t'],
      [(0, 2, 'INTEGER'), '"'],
      [(0, 4, 'OCTET STRING'),
       '\xa1\x03\x80\x01\x03\xa3\x11\xa0\x03\x80\x01\x03\xa4\n\x04\x08\x01\x01\x10PD\x04\x00 ']]],
    [(2, 1),
     [[(0, 2, 'INTEGER'), '\n'],
      [(0, 2, 'INTEGER'), '\x17'],
      [(0, 16, 'SEQUENCE, SEQUENCE OF'),
       [[(2, 0),
         [[(0, 16, 'SEQUENCE, SEQUENCE OF'),
           [[(2, 0), '\xf9'],
            [(2, 1), '\x00'],
            [(2, 2), [[(2, 0), '\x03']]]]],
          [(0, 16, 'SEQUENCE, SEQUENCE OF'),
           [[(2, 0), '\r'],
            [(2, 1), '\x00'],
            [(2, 2), [[(2, 0), '\x03']]]]],
          [(0, 16, 'SEQUENCE, SEQUENCE OF'),
           [[(2, 0), '\xfb'],
            [(2, 1), '\x00'],
            [(2, 2), [[(2, 0), '\x03']]]]],
          [(0, 16, 'SEQUENCE, SEQUENCE OF'),
           [[(2, 0), '\x0e'],
            [(2, 1), '\x00'],
            [(2, 2), [[(2, 0), '\x03']]],
            [(2, 30), [[(2, 1), '\x14']]]]],
          [(0, 16, 'SEQUENCE, SEQUENCE OF'),
           [[(2, 0), '\x0f'],
            [(2, 1), '\x00'],
            [(2, 2), [[(2, 0), '\x03']]]]],
          [(0, 16, 'SEQUENCE, SEQUENCE OF'),
           [[(2, 0), '\xfa'],
            [(2, 1), '\x01'],
            [(2, 2), [[(2, 0), '\x03']]]]]]]]]]],
    [(2, 1),
     [[(0, 2, 'INTEGER'), '\x0b'],
      [(0, 2, 'INTEGER'), '\x17'],
      [(0, 16, 'SEQUENCE, SEQUENCE OF'),
       [[(2, 0),
         [[(0, 16, 'SEQUENCE, SEQUENCE OF'),
           [[(2, 0), '\xf9'],
            [(2, 1), '\x00'],
            [(2, 2), [[(2, 0), '\x02']]]]],
          [(0, 16, 'SEQUENCE, SEQUENCE OF'),
           [[(2, 0), '\r'],
            [(2, 1), '\x00'],
            [(2, 2), [[(2, 0), '\x02']]]]],
          [(0, 16, 'SEQUENCE, SEQUENCE OF'),
           [[(2, 0), '\xfb'],
            [(2, 1), '\x00'],
            [(2, 2), [[(2, 0), '\x02']]]]],
          [(0, 16, 'SEQUENCE, SEQUENCE OF'),
           [[(2, 0), '\x0e'],
            [(2, 1), '\x00'],
            [(2, 2), [[(2, 0), '\x02']]],
            [(2, 30), [[(2, 1), '\x14']]]]],
          [(0, 16, 'SEQUENCE, SEQUENCE OF'),
           [[(2, 0), '\x0f'],
            [(2, 1), '\x00'],
            [(2, 2), [[(2, 0), '\x02']]]]],
          [(0, 16, 'SEQUENCE, SEQUENCE OF'),
           [[(2, 0), '\xfa'],
            [(2, 1), '\x01'],
            [(2, 2), [[(2, 0), '\x02']]]]]]]]]]],
    [(2, 1),
     [[(0, 2, 'INTEGER'), '\x0c'],
      [(0, 2, 'INTEGER'), '\x1f'],
      [(3, 1), [[(2, 1), [[(2, 0), '\x02']]]]]]],
    [(2, 1),
     [[(0, 2, 'INTEGER'), '\r'],
      [(0, 2, 'INTEGER'), '\x1f'],
      [(3, 1), [[(2, 1), [[(2, 0), '\x03']]]]]]],
    [(0, 0, 'reserved for BER')]]]]]
```

**Comment by H21lab** [comment]
I think the packet was from this pcap http://www.pcapr.net/view/nos/2011/3/1/13/attach_sccp_xudts.pcap.html

SCCP XUDT messages were resembled by wireshark. (this could be the reason why the tcap_raw is bigger than frame_raw in that input json). Inside the TCAP there are multiple TCAP components. But wireshark displays also the BER Error on decoding it.

And possibly the similar approach can be used for other protocols. To test pycrate encoders/decoders by feeding it from tshark by using some public pcaps.

**Pull request merged**
