### PR TITLE
fix set empty set([]) in bitstring object

### PR DESCRIPTION
**Pull request by p1-scg**
Hello,

I would like to set value with empty set([]) in bitstring object.
But I can't do it. line 157 (moff = max(off) accept only none empty list)

Thank you.

### CODE REVIEW

**Comment by mitshell** [comment]
Hi,
Thanks for the PR.
On my side, I just committed 2 patches that not only enable empty set of named bits, but also empty BIT STRING (i.e. a null length bit string). I'll let you test it, and if OK, I'll disable the PR.

**Comment by p1-scg** [comment]
Hi,

Could I see the two patches that you are referring to ?
I will take time to test it. =)

**Comment by mitshell** [comment]
This https://github.com/ANSSI-FR/pycrate/commit/70ade3ca32d1178cf3afabf5f2e6df9af9102313
And this https://github.com/ANSSI-FR/pycrate/commit/fdfd19633664644fd8aa94ae20eeb844b9c8b88b

**Comment by p1-scg** [comment]
Hello,
For me, your patches are ok.
Could you disable the PR, and add
your patches to the master branch ?

**Pull request closed without merging**
